---
server:
  port: 8888
security:
  basic:
    enabled: true
  user:
    name: itsme
    password: itsme  
spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/franklin-antony/spring-cloudconfig-settings"
          search-paths:
          - 'station*'
              