---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/franklin-antony/spring-cloudconfig-settings"
          search-paths:
          - 'station*'
              